### ISSUE TITLE
Not working on MacOSX 10

### ISSUE THREAD

**Issue by dvutova** [mozkeeler/signTextJS#18]
The libnss3.dylib could not be loaded (main.js line 23).
![firefox_signtext_mac](https://cloud.githubusercontent.com/assets/10516534/5721969/7b92266e-9b40-11e4-907e-de5f9f598390.jpg)

**Comment by shugg** [comment]
I can confirm that this add-on is not working on OS X. Windows works like a charm.

**Comment by mozkeeler** [comment]
This should be fixed by #20.
