### ISSUE TITLE
Signature from cyrillic doesn't validation

### ISSUE THREAD

**Issue by MrEfrem** [mozkeeler/signTextJS#19]
The signature created from cyrillic of the text doesn't validation (FF35).

**Comment by MrEfrem** [comment]
Text charset Windows-1251.

**Comment by MrEfrem** [comment]
There can be in this line of a code a problem:
```
converter.charset = "UTF-8"; // XXX TODO: use current document's charset
```
because Windows-1251 page encoding.

**Comment by mozkeeler** [comment]
Thanks for filing this. Looks like the same as issue #2.
