### ISSUE TITLE
Certificate enumeration problem

### ISSUE THREAD

**Issue by ValeryEliseev** [mozkeeler/signTextJS#21]
In signTextJS v. 0.6 certificate list gets filled incorrectly, loosing some certificates in process.
Non-unique field 'nickname' is being used as certificate array key (see main.js, lines 243-247).
If two certificates were issued for some subject by one issuer, their 'cert.nickname' values could be identical. 
Hence, adding new array element replaces an existing element.
By the same reason the certificate's serial number should be added to the value in the drop-down list.
Invalid (expired or not valid yet) certificates should be marked in list as 'EXIPRED'.

I do not know how to do it right. Unique field 'cert.sha1Fingerprint' better as an array key, 
but CERT_FindUserCertByUsage require "nickname" to find cert.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=403910 
(CERT_FindUserCertByUsage() returns wrong certificate if multiple certs with same subject available)

**Comment by akostadinov** [comment]
I noticed with 0.7.2 that correct certificate is not always selected. User has to notice which certificate is in use before signing. Ideal would be to select client certificate requested by the web site.

**Comment by jasp00** [comment]
#38 does not use nicknames as keys. Expired certificates do not appear in the list.

**Comment by akostadinov** [comment]
In the past I saw that when you have multiple valid certs, the desired one is not always selected. Now I only have one user cert so can't say if this has been fixed or not.
