### ISSUE TITLE
Add-on not working on Firefox 35 (after automatic update).

### ISSUE THREAD

**Issue by donangel** [mozkeeler/signTextJS#22]
*Using signTextJS 0.5 from Dec 17 2014, Firefox 35.0*

After Firefox (Portable) got updated automatically, the add-on stopped working.

The add-on is shown as active in the Add-ons Manager, but when I try to sign anything, i get the same message as when the add-on was non-existent (i.e., *"your browser does not support...."*). The e-signature works OK, because just before trying to sign, I logged in with the e-signature (so I'm waving off problems with the hardware).

Any idea what to try here?

Thanks,
D.

**Comment by sharapanoff** [comment]
see Browser Console for any errors
in my case #6 after the fix for windows, the addon failed to load in my profile, so i had to create a new one

**Comment by donangel** [comment]
I have some updates pending, hopefully that'll resolve the problem.

If not, I will create new profile and proceed with it.

I will update the issue accordingly, maybe next week, when I have new payment to make (I cannot make test payment, as this is living bank account).

/D

**Comment by donangel** [comment]
Resetting profile worked. 

Closing.
