### ISSUE TITLE
Default Enter action is cancel which differs from the previous behaviour

### ISSUE THREAD

**Issue by lukavia** [mozkeeler/signTextJS#24]
Hi, 
Than you very much for this plug-in. It is life saving for those of use actively using certificates. 

I have one small issue. I've lost several hour to figure out why sometimes one of my certificates worked and sometimes it didn't. I finally figure out that I have a habit in the sing dialog to enter my pin and hit enter. It seams that this by default means Cancel button where I'm used to mean OK. 
In the rare cases where my certificate worked I've clicked on OK with the mouse, which is somewhat annoying since I use the keyboard for speed. 

Thanks in advance

**Comment by donangel** [comment]
+1 for this one. Just today I cancelled two times by mistake, becase of hitting Enter, instead of clicking with the mouse... 

I guess the default button, if such thing exists in this world, should be on the OK button. 

Best regards, 
Doncho

**Comment by mozkeeler** [comment]
Fixed by #23 (although the xpi hasn't been regenerated, so that won't work out-of-the-box at the moment).
