### ISSUE TITLE
TODO: Use the charset from the document calling window.crypto.signText

### ISSUE THREAD

**Issue by BiserStoev** [mozkeeler/signTextJS#25]
replace this row:

converter.charset = "UTF-8";

with:

let domWindow = utils.getMostRecentBrowserWindow();
converter.charset = domWindow.content.document.characterSet;

Regards!

**Comment by vbadev** [comment]
This will not work in all cases. If signText is called from document embedded in iframe this code will return character set of embeding document instead of calling document.

**Comment by BiserStoev** [comment]
This is not a good idea - to call “signText” from document embedded in the iframe. 
Usually, if we have а process in the iframe, it must remain closed there.

In any case, the proposal is better than the current state of this element of the code, right?

Regards!

**Comment by vbadev** [comment]
It may not be good idea but is possible. To have site that uses Windows-1251 encoding in 2015 is bad idea too, but at least one Bulgarian bank still uses this charset.

I just wanted to point obvious problem. Yet I do not know if there is better way to do it and this will probably solve encoding problem for all users of signText.

**Comment by mozkeeler** [comment]
This was fixed by #26.
