### ISSUE TITLE
UI issue on MacOSX

### ISSUE THREAD

**Issue by lobachpavel** [mozkeeler/signTextJS#28]
There is UI issue when running extension in FireFox 35.0.1 on MacOSX 10.10.2
Certificate selection dialog looks transparent and doesn't have a border
screenshot attached
![crypto_extension_firefox_macos](https://cloud.githubusercontent.com/assets/10192314/6123040/e55c826e-b10d-11e4-8bee-8b69525b8769.png)

**Comment by PlamenVasilev** [comment]
I have this problem too.

**Comment by lordross** [comment]
Same here.
