### ISSUE TITLE
FF 37.0.1 (Ubuntu 64bit) TypeError: theWindow.crypto.signText is not a function

### ISSUE THREAD

**Issue by baromojm** [mozkeeler/signTextJS#30]
Hi, with Firefox 37.0.1 on Ubuntu 14.10 64bit, I always get the error:
TypeError: theWindow.crypto.signText is not a function

I have tried both versions of the extension: 0.6 and 0.7.2

Regards,

**Comment by vbadev** [comment]
If you open Firefox with local file as parameter you must reload the page to activate signTextJS. This function is injected in document on content-document-global-created event, but it is not fired when Firefox is started with local file.

**Comment by jasp00** [comment]
If this is the problem, it should be solved with #38.
