### ISSUE TITLE
wrong password should be detected and user asked to try again

### ISSUE THREAD

**Issue by akostadinov** [mozkeeler/signTextJS#31]
With firefox 37 I see that if I type the wrong password for the password store, then add-on does not give any warning. Just it seems text is not signed properly and the site requesting signature throws an error. It would be less confusing if upon wrong password, the user is asked to try again.

Thanks for the plug-in. It saves the day.

**Comment by jasp00** [comment]
Current behavior (after the fix in #38) is to show "error:authenticationFailed". Older browsers used to ask the password again.
