### ISSUE TITLE
After updating to firefox 44 - signtextjs doesn't work

### ISSUE THREAD

**Issue by motomx** [mozkeeler/signTextJS#36]
my system:
WIN 7 (64x)
firefox 44

when I try to sign it gives the following error: Internalerror

**Comment by motomx** [comment]
here's the error 

SignText: using '***********censored*************' main.js:24
SignText: SEC_PKCS7CreateSignedData failed main.js:24
SignText: NSS error: The certificate was signed using a signature algorithm that is disabled because it is not secure. (-8016)

**Comment by mozkeeler** [comment]
You might have to import and trust (to identify email users) the root certificate that issued your signing certificate.

**Comment by motomx** [comment]
I checked for that like a hundred times.
My root CA is imported and selected as trusted. (all 3 checkboxes checked)
I don't understand what is going on. As soon as I upgrade to firefox 44,  the signing in one particular banking site and their certificates, just breaks. When I downgrade FF it continues to error. When I uninstall firefox (delete everything) and install v43 and restore from backup - all is working again. 

Is that making any sense ...? I think there's something in my private certificate + FF 44 + signtextjs that makes this error.

I have confirmed this on another system (WIN 7 , x64) with the same bank. FF 44 just breaks it and makes signing impossible.

**Comment by mozkeeler** [comment]
Does it work in 44 if you start with a new profile?

**Comment by motomx** [comment]
After conducting some tests i can say the following. Prior to version 44 everything is working after updating to version 44+ for some reason... some of the certificates do work, some don't. I think it has something to do with the Root CA of the bank , but I can't say exactly what. I will test with a new profile but I don't think that is the problem.

**Comment by bobgomez** [comment]
I found this in Firefox's site:

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

I seems that starting FF44 this add-on won't work (as it did until FF43) because it is not signed by Mozilla. It says that one FF45 be release  (only FF ERS), this add-on won't be need anymore. Meanwile, either someone makes this add-on be signed by Mozilla (!), either there is an option to deactivate (at your own risk) this limitation (see article).

NOTE: Personally I havn't test this yet, so I can't tell if it fixes the issue.

**Comment by mozkeeler** [comment]
@bobgomez: This add-on (as hosted at https://addons.mozilla.org/en-US/firefox/addon/signtextjs/ ) is signed by Mozilla. Add-on signing is unrelated to the functionality this add-on provides.

**Comment by bobgomez** [comment]
Well, I just said what my FF says after updating to 44. The add-on menu shows that the plugin has been deactivated automatically [see image] (translation of the message: "signTextJS could not be verified for use in Firefox and has been disabled."). The link 'more info' takes me to the link I attach in my prevoius post. 

![aa](https://cloud.githubusercontent.com/assets/17344825/13336698/c7cd4f36-dc17-11e5-8dab-e605cce692cd.jpg)

I'm not questioning, just providing info if that helps to solve this issue. 

Regards.

**Comment by mozkeeler** [comment]
The symptoms you are describing are different from the ones originally described in this issue, so it would be helpful if you could open a new issue so we can discuss it there without confusing this issue too much.
