### ISSUE TITLE
Doesn't work in Firefox 48 with Electrolysis enabled.

### ISSUE THREAD

**Issue by rahmanroman** [mozkeeler/signTextJS#40]
In my Firefox 48 with manually enabled Electrolysis (via browser.tabs.remote.autostart = true) extensions is enabled but doesn't work (window.crypto.signText is undefined). Please keep in mind that this settings will be enabled by default from Firefox 49. Check more info http://arewee10syet.com/

I'm sure that your solution is the last hope to use  Firefox for online banking etc. Thanks a lot for your work.

**Comment by pivanov83** [comment]
Any update on this? As of right now SignTextJS does not work at all in Firefox developer edition (51.0a2), with or without multi process. With multi-process enabled we get window.crypto.signText is undefined. With multi-process off the add-on fails with java script error: TypeError: cert.getUsagesString is not a function at main.js:306:5. With FireFox 50 arriving in few weeks from now (hopefully without Electrolysis in it) this issue will become even more critical.

**Comment by Musikolo** [comment]
I had the same issue using Firefox 50.1 in Windows and Linux. I tried with a new user and factory-configured Firefox in Linux, and it worked good though. Pretty weird the whole thing!!

**Comment by fiery-** [comment]
signTextJS v0.7.7 works fine in Firefox 53, but only if e10s is disabled. Otherwise "window.crypto.signText" is undefined.
