### ISSUE TITLE
Get stronger hash alg

### ISSUE THREAD

**Issue by julien2512** [mozkeeler/signTextJS#43]
I need something like
SEC_OID_PKCS1_SHA256_WITH_RSA_ENCRYPTION
but the original API seems not to let us choose the hash alg.

**Comment by julien2512** [comment]
Look at my commit.
But I need to sleep a bit (lol). I will test it out later (may be this weekend).

**Comment by ousia** [comment]
@mozkeeler,

besides this pull request (which according to @julien2512 can’t be merged), would it be possible that you replace SHA1 with SHA256?

**Comment by mozkeeler** [comment]
Due to compatibility concerns and the reasons explained here: https://github.com/mozkeeler/signTextJS/issues/49#issuecomment-297165905 I don't think it's worth changing the hash algorithm.
