### ISSUE TITLE
Plugin does not work on Firefox 50

### ISSUE THREAD

**Issue by ValeryEliseev** [mozkeeler/signTextJS#48]
Plugin SignTextJS does not work on Firefox 50. Tested on Windows and MacOS.

**Comment by ndias** [comment]
I can confirm also don't work in Linux with firefox 50

**Comment by Musikolo** [comment]
I had the same issue with Firefox 50.1 and I found the problem was I enabled manually Electrolysis feature some time ago. More info at https://github.com/mozkeeler/signTextJS/issues/40#issuecomment-270290155

I hope it helps! ;-)

**Comment by rbatllet** [comment]
With Firefox 51.0.1 and SignTextJS 0.7.5 it works great!

![signature](https://cloud.githubusercontent.com/assets/3993987/22628683/c49004d6-ebd8-11e6-8626-118eac62da11.png)
