### ISSUE TITLE
ff53 - list of certificates shows "undefined" and can't sign (null pointer)

### ISSUE THREAD

**Issue by sharapanoff** [mozkeeler/signTextJS#49]
![ff53](https://cloud.githubusercontent.com/assets/10178310/25285743/f7714416-26c3-11e7-9c77-6e97fa40bae9.png)

it is related to [857627](https://bugzilla.mozilla.org/show_bug.cgi?id=857627)

**Comment by mozkeeler** [comment]
Thanks for filing this. This should be fixed by 404c673a82cb76a05ba2ef9baf07ce6829ca00d5. Do you mind testing? ( https://github.com/mozkeeler/signTextJS/blob/master/signtextjs.xpi )
I also updated the version on addons.mozilla.org, but that might take some time to be reviewed and accepted.

**Comment by sharapanoff** [comment]
i've installed this new version (from github) and it works OK

**Comment by dab18** [comment]
signTextJS 0.7.6 broke hundreds of our customers today, those who use the Firefox-ESR (45.9.0 52.0.2 52.1.0).

jsconsole says:
SignText: using 'undefined' main.js:27
SignText: signText failed: Error: Failed to decode base64 string! main.js:27

signing dialog show info about certificate, but select with certs list is empty (no nickname).

crypto.signtext() returns "error:internalError"

as a workaround we recommended install "signTextJS plus 0.8.6" (not broken 
yet)

**Comment by sharapanoff** [comment]
@dab18  the description of this version is:
Version 0.7.6 
Works with **Firefox 53.0 and later** 
don't install it on 45-52

version 0.8.6 of "signTextJS plus" dosn't work on FF53 (has empty rows on certificate chooser) - expect new version soon

**Comment by dab18** [comment]
signTextJS automatically updated to version 0.7.6
install.rdf say <em:minVersion>38.0a1</em:minVersion>

**Comment by dab18** [comment]
Help, please! Now we have more than 1000 broken clients.
We can not instantly update all the firefox to version 53 - these are our customers and not our employees.
This is very important for our business.

PR #50 fixes the problem.
Please review it, and release 0.7.7(?) on https://addons.mozilla.org/ru/firefox/addon/signtextjs/
as fast as possible.

**Comment by mozkeeler** [comment]
I've merged the fix and put up a new version for review on amo.
However, you should be aware that when Firefox 57 is released, this add-on will no longer work (all legacy add-ons will no longer work in release versions of Firefox as of that time). Due to the nature of this add-on, it is not possible to port it to the new framework (webextensions). I have no plans to create a replacement anyway. The API this mimics was removed from Firefox nearly two and a half years ago. This was intended as a crutch users could rely on while websites migrated away from signText. The crutch is going away, and if sites don't have a replacement yet, there's nothing I can do about that.

**Comment by dab18** [comment]
thanx a lot!
customers who updated signTextJS to 0.7.7 works again.

**Comment by dab18** [comment]
after 20 years crutch like crypto.signtext()...
after 20 years crutch like http://secclab.mozdev.org/
after 20 years crutch like https://addons.mozilla.org/ru/firefox/addon/signtextjs/
after 20 years crutch like ... "Firefox ESR" is "stable", "enterprise" "grade" "browser"... (all quoted)
that's "shameful","poor"..."несостоятельный","жопа","костыль" (sorry, "google-translate")!...webcrypto?
we need "simple","standart", "API"?

**Comment by dab18** [comment]
i think leave "crypto.signtext()" "as is" over 20 years, is a best way to keep "standart way" with no alternatives like poor "webcrypto" "standards".

**Comment by dab18** [comment]
we used "crypto.signtext()" for our customers about 20 years, from Netscape Navigator 4.X and now only way is to switch it to Interner Explorer with "certified plugin"

**Comment by sharapanoff** [comment]
@dab18 this is not the right place to complain - the issue i've opened was just about FF 53 and signTextJs 0.7.5

and it is too late - it all began 3 years ago [1083118](https://bugzilla.mozilla.org/show_bug.cgi?id=1083118) and this year will end it - your post is a perfect Epitaph
