### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by justnick** [mozkeeler/signTextJS#53]
Hi There,

Any plans to port this to Quantum?
Not sure whether it's possible at all, but add-on is now marked as "legacy" and not working on Quantum (Firefox 57 and above).

**Comment by mozkeeler** [comment]
Architecturally it would be difficult to implement, and the necessary APIs aren't available to webextensions anyway, so no, this will not be available in Firefox 57 and above.

**Comment by justnick** [comment]
I understand.

Thanks for taking the time to respond.
